### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by tortfeaser** [hassio-addons/addon-tasmoadmin#57] opened 2019-10-30 23:10 UTC
## Proposed changes

A suggestion for a UI improvement. Can you please add the switch for 'show in sidebar' that links the GUI? Its one two less clicks to administer these Tasmota devices.

**Comment by sinclairpaul** [comment] 2019-10-30 23:11
Duplicate of #54

**Closed by sinclairpaul** 2019-10-30 23:11 UTC

**Comment by tortfeaser** [comment] 2019-10-30 23:15
That's hilarious. Sorry. Crossed wires minutes apart.
