### ISSUE TITLE
JSON ERROR

### ISSUE THREAD

**Issue by devianpctek** [hassio-addons/addon-tasmoadmin#28] opened 2018-09-28 15:42 UTC
Hello, I'm trying to add my device but I'm getting this error when I get to this screen
![screenshot from 2018-09-28 10-39-50](https://user-images.githubusercontent.com/1848859/46218680-e393be80-c30a-11e8-8b05-d4a30b745d10.png)
and click on search, If I try the autoscan, it shows no devices found, although I have one running.
 
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer =>

**Comment by devianpctek** [comment] 2018-09-28 15:57
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin v0.5.1

 Centrally manage all your Sonoff-Tasmota devices

 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 amd64 / Debian GNU/Linux buster/sid / HA 0.78.3 / SU 131 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 12-migrate.sh: executing... 
[cont-init.d] 12-migrate.sh: exited 0.
[cont-init.d] 13-persistent-data.sh: executing... 
[cont-init.d] 13-persistent-data.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by tjorim** [comment] 2018-09-28 16:39
Duplicate of #16. Anyway, it's an issue with TasmoAdmin itself, not this add-on.

**Closed** 2018-09-28 21:05 UTC
